# fail_any_type_error_on_error
AnyAssertionError: unexpected value
--- found ---
Error("")
--- expected ---
any(TypeError)
--- path ---
actual

# fail_any_string_on_number
AnyAssertionError: unexpected value
--- found ---
10
--- expected ---
any(String)
--- path ---
actual

# fail_any_stirng_on_boolean
AnyAssertionError: unexpected value
--- found ---
true
--- expected ---
any(String)
--- path ---
actual.token

# fail_any_number_on_string
AnyAssertionError: unexpected value
--- found ---
"dam"
--- expected ---
any(Number)
--- path ---
actual[0].age

# fail_custom_instance
AnyAssertionError: unexpected value
--- found ---
{}
--- expected ---
any(User)
--- path ---
actual

